server:
  port: 8082 # spring boot port


#logging:
#    config: classpath:logback-spring.xml # logback configuration

rpc:
  server:
    zk: # zookeeper configuration
      root: /rpc
      addr: 34.121.183.167:2181
      timeout: 10000
  network: # This section needs to be manually added; server config for rpc communication
    port: 28889
    address: localhost # manually fill in the IP address of the current machine


